strict-sigcheck = false

[YouTube-Stable]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
arch = "arm64-v8a"

[YouTube-Stable.patches]
"github:MorpheApp/morphe-patches" = []

[YT-Music-Stable]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"
patcher-args = "-e 'Change header' -Ocustom=icons/Music/header"

[YT-Music-Stable.patches]
"github:MorpheApp/morphe-patches" = []

[Instagram]
brand = "piko"
github-dlurl = "https://github.com/krvstek/uni-storage/releases/tag/instagram"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
# uptodown-dlurl = "https://instagram.en.uptodown.com/android"
arch = "arm64-v8a"

[Instagram.patches]
"github:crimera/piko" = []


[Google-Photos]
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
arch = "arm64-v8a"
patcher-args = "-e 'Enable DCIM folders backup control'"

[Google-Photos.patches]
"github:RookieEnough/De-Vanced" = []
